## Numpy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks. 

Installation Instrution

Go to command prompt (Administrator) and type the following instruction 
   
>conda install numpy

#### Importing NumPy in python notebook

In [1]:
import numpy as np

## Creating NumPy array

#### Using python lists

In [3]:
list1 = [[1,2,3],[4,5,6]]
arr1 = np.array(list1)

In [4]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
list2 = [[1,2,3],[1,1,1],[5,6,7]]
arr2 = np.array(list2)

In [6]:
arr2

array([[1, 2, 3],
       [1, 1, 1],
       [5, 6, 7]])

#### Built in methods

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [16]:
np.linspace(0,10,21)
#This will give us 21 numbers between [0,10]. Both 0 and 10 included

array([  0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,
         4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,
         9. ,   9.5,  10. ])

In [18]:
#Identity matrix
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

#### Generating random numbers

In [19]:
np.random.rand(2)

array([ 0.30010834,  0.57308498])

In [20]:
np.random.rand(5,5)

array([[ 0.81592959,  0.58914536,  0.82049611,  0.23982349,  0.96424021],
       [ 0.035252  ,  0.29417309,  0.3729404 ,  0.05375264,  0.40001844],
       [ 0.69715933,  0.03154647,  0.2537868 ,  0.98037708,  0.49097168],
       [ 0.55004115,  0.78239235,  0.75642927,  0.5861231 ,  0.48708367],
       [ 0.56723603,  0.20088955,  0.49904357,  0.33569838,  0.99446335]])

In [21]:
np.random.randn(10)

array([-0.34509621,  1.05257379, -0.66437889,  0.2932506 ,  0.95253883,
       -0.24222613, -0.96166241, -0.31260677, -1.5055132 ,  0.60298978])

>np.random.rand will give us the random values from UNIFORM DISTRIBUTION 
>np.random.randn will give us the random values from STANDARD NORMAL DISTRIBUTION (mu=0, sigma=1)

In [22]:
#Random integer between two numbers
np.random.randint(1,100)

4

In [24]:
# 10 random integers between 0 and 100
np.random.randint(1,100,10)

array([65, 42,  4, 63, 26, 42,  7, 12, 92, 81])

### Shape and Reshape

In [25]:
arr1 = np.random.randint(1,100,50)

In [26]:
arr1

array([65, 42, 76, 60, 77, 89, 54, 45,  6, 21, 75, 88, 70, 89, 73, 78, 73,
       34, 13, 84, 93, 44,  6, 63, 34, 21, 17,  1, 90, 80,  5, 68, 87,  5,
       66, 82, 56,  7, 50, 83, 19, 81, 90, 47, 45, 64, 38, 48, 45, 35])

In [27]:
arr1.shape

(50,)

In [29]:
arr1.reshape(5,10)

array([[65, 42, 76, 60, 77, 89, 54, 45,  6, 21],
       [75, 88, 70, 89, 73, 78, 73, 34, 13, 84],
       [93, 44,  6, 63, 34, 21, 17,  1, 90, 80],
       [ 5, 68, 87,  5, 66, 82, 56,  7, 50, 83],
       [19, 81, 90, 47, 45, 64, 38, 48, 45, 35]])

In [30]:
arr1.shape

(50,)

In [31]:
arr2 = arr1.reshape(5,10)

In [32]:
arr2.shape

(5, 10)

### min, max, argmin, argmax

>These methods are useful for finiding max or min values using max() or min() argument. 
>argmax() or argmin() are used to find the index locations of max and min values 

In [33]:
arr1

array([65, 42, 76, 60, 77, 89, 54, 45,  6, 21, 75, 88, 70, 89, 73, 78, 73,
       34, 13, 84, 93, 44,  6, 63, 34, 21, 17,  1, 90, 80,  5, 68, 87,  5,
       66, 82, 56,  7, 50, 83, 19, 81, 90, 47, 45, 64, 38, 48, 45, 35])

In [34]:
arr1.max()

93

In [35]:
arr1.min()

1

In [36]:
arr2

array([[65, 42, 76, 60, 77, 89, 54, 45,  6, 21],
       [75, 88, 70, 89, 73, 78, 73, 34, 13, 84],
       [93, 44,  6, 63, 34, 21, 17,  1, 90, 80],
       [ 5, 68, 87,  5, 66, 82, 56,  7, 50, 83],
       [19, 81, 90, 47, 45, 64, 38, 48, 45, 35]])

In [37]:
arr2.argmax()

20

>here, location 20 means 21st element in the array. Since it has 5 rows and 10 columns, the matrix location would be [2,0]

In [38]:
arr2.argmin()

27

In [44]:
arr2[2,7]

1

## NumPy Indexing

### Bracket Indexing

In [50]:
arr1 = np.arange(0,11)

In [51]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr1[8]

8

In [55]:
arr1[4:8]
#5th 6th 7th and 8th element of an array

array([4, 5, 6, 7])

### Broadcasting

>Numpy arrays different from a normal python list because of their ability to broadcast. Broadcsting is setting a value with index range

In [56]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr1[4:7] = 100
arr1

array([  0,   1,   2,   3, 100, 100, 100,   7,   8,   9,  10])

In [59]:
#Lets try this with list
list1 = [0,1,2,3,4,5,6,7,8,9,10]

#Show
list1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [62]:
list1[5:8] = 100

TypeError: can only assign an iterable

In [64]:
list1[5] = 100

#Show
list1

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9, 10]

### Slicing

>Slicing is another differentiating feature. 

In [65]:
arr2 = np.arange(0,11)

#show
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
slicearr2 = arr2[0:6]

#Show
slicearr2

array([0, 1, 2, 3, 4, 5])

In [67]:
slicearr2[:] = 100

#Show slice again
slicearr2

array([100, 100, 100, 100, 100, 100])

> Now let us again print the original array. What do you expect?

In [68]:
arr2

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

>Note that the changes also occur in our original array! 
>Data is not copied, its a view of the original array which avoids memory problems! 

>So how to copy the array? 

In [69]:
arr2_copy = arr2.copy()

#show
arr2_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

### 2D indexing

In [74]:
arr1 = np.arange((100))

arr1 = arr1.reshape(10,10)
    
#Show
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [75]:
arr1[0:5,0:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [76]:
arr1[0:6:2,0:6:2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

# Add that image from google

> Indexing of a 2d matrix can be a bit confusing. Try google image searching NumPy indexing to find useful images like this

### Selection

In [77]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [81]:
arr1 > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

In [82]:
boolarr1 = arr1 > 50

In [83]:
arr1[boolarr1]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## Numpy Arithmetic Operations 

In [84]:
arr = np.arange(0,9)

In [85]:
arr = arr.reshape(3,3)

In [86]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [88]:
arr * arr

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [89]:
arr/arr

C:\Users\ajnad\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ nan,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

>It gives warning message as we are dividing 0 by 0. It replaces the value by nan(not a number)

In [90]:
1 / arr

C:\Users\ajnad\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[        inf,  1.        ,  0.5       ],
       [ 0.33333333,  0.25      ,  0.2       ],
       [ 0.16666667,  0.14285714,  0.125     ]])

>again, 1/0 is infinity

In [91]:
arr **3

array([[  0,   1,   8],
       [ 27,  64, 125],
       [216, 343, 512]], dtype=int32)

## Universal array functions

In [96]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [100]:
arr1 = arr ** 2

In [101]:
np.sqrt(arr1)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [99]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
np.exp(arr)

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00],
       [  2.00855369e+01,   5.45981500e+01,   1.48413159e+02],
       [  4.03428793e+02,   1.09663316e+03,   2.98095799e+03]])

In [103]:
np.sin(arr)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [104]:
np.log(arr)

C:\Users\ajnad\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[       -inf,  0.        ,  0.69314718],
       [ 1.09861229,  1.38629436,  1.60943791],
       [ 1.79175947,  1.94591015,  2.07944154]])

>np.TAB to see all the functions